[project]
name = "controller"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chatterbox-tts>=0.1.7",
    "httpx>=0.28.1",
    "numpy>=1.26.4",
    "ollama>=0.6.2",
    "setuptools>=84.0.0",
    "sounddevice>=0.5.6",
    "websockets>=17.1",
]
